# Generated by Django 5.2.8 on 2025-11-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazon_DB',
            fields=[
                ('Product_name', models.CharField(max_length=20)),
                ('S_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_type', models.CharField(max_length=20)),
                ('Price', models.CharField(max_length=20)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
